name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install Poetry
      run: |
        python -m pip install poetry
    - name: Publish
      run: |
        poetry publish --build --username __token__ --password ${ secrets.PYPI_API_TOKEN }
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/*"